- name: Configure frontend server
  hosts: web 
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed 

  - name: Start & Enable the nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
  
  - name: delete the default content 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent #this will remove the html folder completely since it deleted we will cretae the html folder again and import our code

  - name: create the html directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download & extract the code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy the backend Configuration
    ansible.builtin.copy:
      src: Frontend.service # give the file name of where we connected with backend server
      dest: /etc/nginx/default.d/expense.conf

  - name: Restart the nginx 
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted 